name: Periodic healthcheck

on:
  schedule:
    - cron: '*/10 * * * *'

#on:
#  push:
#    branches:
#      - master

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://stormy-bastion-03047.herokuapp.com/
