name: Deployment Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: skip
        if: ${{ contains(join(github.events.commits.*.message), '#skip') }}
        run: echo "skip"
      - name: not skip
        if: ${{ !contains(join(github.events.commits.*.message), '#skip') }}
        run: echo "not skip"
      - name: testing
        env:
          MESSAGES: ${{ github.events.commits.*.message }}
          JOINED: ${{ join(github.events.commits.*.message) }}
          CONTAINS: ${{ contains(join(github.events.commits.*.message), '#skip') }}
        run: echo "$MESSAGES" "$JOINED" "$CONTAINS"
